# copied from creasty/rid
version: '2.1'

services:
  app:
    image: creasty/rid:dev
    build: .
    volumes_from:
      - volume
    extra_hosts:
      localhost: "${DOCKER_HOST_IP}"
    command: tail -f /dev/null

  volume:
    image: alpine:latest
    volumes:
      - /app/vendor
    command: tail -f /dev/null
